all:
	pdflatex -shell-escape Install_PVE.tex && pdflatex -shell-escape Install_PVE.tex && evince Install_PVE.pdf &

clean:
	rm -f *.aux *.toc *.log *.nav *.out *.snm *~ *.vrb
	rm -rf _minted-Install_PVE

