all:
	pdflatex -shell-escape PVE-install.tex && pdflatex -shell-escape PVE-install.tex && evince PVE-install.pdf &

clean:
	rm -f *.aux *.toc *.log *.nav *.out *.snm *~ *.vrb
	rm -rf _minted-PVE-install

